# Generated by Django 3.0.7 on 2020-06-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[(0, 'Cancelled'), (1, 'Order Confirmed')], default=1, max_length=2, null=True)),
                ('order_date', models.DateField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student')),
                ('courses', models.ManyToManyField(to='myapp.Course')),
            ],
        ),
    ]
