# Generated by Django 3.0.7 on 2020-06-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='optional',
            field=models.TextField(null=True),
        ),
    ]
