# Generated by Django 3.0.7 on 2020-06-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='optional',
        ),
    ]
