# Generated by Django 3.0.7 on 2020-06-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
