# Generated by Django 3.0.8 on 2020-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20200820_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=40.0),
        ),
    ]
